/**
 * Oenology Flashcards — 50-card foundational deck (Feb 2026, Rich).
 *
 * Dual-language format on every card:
 *   • `sop`   — SOP / technical language, as it would appear in a cellar
 *                procedure document or AWRI reference. Reads like real
 *                winemaker-speak. Rich uses this to sound fluent on calls.
 *   • `plain` — plain-English translation, as if a working winemaker
 *                explained it to a mate over a pint. This is how Rich
 *                actually learns it.
 *
 * Rich's mental model: "Say it SOP; understand it plain."
 *
 * Scope matches the site promise from /ask:
 *   "Ask anything about wine science, flavours, regions, or pairings.
 *    Powered by real oenology."
 *
 * Editing: change any card's `id` and you erase learner progress on it.
 * Add new cards freely; the Leitner scheduler picks them up automatically.
 */

export type FlashcardCategory =
  | "sugar-ferment"
  | "acid-ph"
  | "so2"
  | "mlf"
  | "oak-aging"
  | "faults"
  | "sensory"
  | "regions"
  | "pairing"
  | "consulting"
  | "business"
  | "viticulture";

export interface Flashcard {
  id: string;
  term: string;
  category: FlashcardCategory;
  sop: string;           // SOP / technical
  plain: string;         // plain-English translation
  why: string;           // winemaker relevance (plain)
  when: string;          // decision / measurement point (plain)
  ruleOfThumb?: string;  // optional numeric heuristic
  cited?: string;        // optional academic source
}

export const CATEGORY_META: Record<
  FlashcardCategory,
  { label: string; short: string }
> = {
  "sugar-ferment": { label: "Sugar & Fermentation", short: "Sugar" },
  "acid-ph":       { label: "Acid & pH",             short: "Acid" },
  so2:             { label: "SO₂ & Preservation",   short: "SO₂" },
  mlf:             { label: "Malolactic",            short: "MLF" },
  "oak-aging":     { label: "Oak & Aging",          short: "Oak" },
  faults:          { label: "Faults",                short: "Faults" },
  sensory:         { label: "Sensory & Flavour",    short: "Sensory" },
  regions:         { label: "Regions & Climate",    short: "Regions" },
  pairing:         { label: "Pairing Principles",   short: "Pairing" },
  consulting:      { label: "Consultant's Toolkit", short: "Consult" },
  business:        { label: "Business of Wine",     short: "Business" },
  viticulture:     { label: "Vineyard & Viticulture", short: "Vine" },
};

export const FLASHCARDS: Flashcard[] = [
  // ── SUGAR & FERMENTATION (10) ─────────────────────────────────────────
  {
    id: "brix",
    term: "Brix (°Bx)",
    category: "sugar-ferment",
    sop: "Refractometric or hydrometric measurement of dissolved soluble solids in grape juice, expressed as °Brix; approximates sucrose grams per 100g solution. Refractometer readings require temperature compensation from the 20°C reference.",
    plain: "It's the sugar in the juice. Higher number = more sugar = higher potential alcohol. Put a drop on a refractometer, read the number.",
    why: "Sets the ceiling for potential alcohol. Tracks ripeness pre-harvest and how far along your ferment is.",
    when: "Weekly during ripening; twice daily during peak ferment.",
    ruleOfThumb: "1°Bx ≈ 0.55–0.60% v/v potential alcohol.",
    cited: "Zoecklein · Wine Analysis & Production, ch. 3",
  },
  {
    id: "baume",
    term: "Baumé (°Bé)",
    category: "sugar-ferment",
    sop: "Density-based sugar scale used predominantly in Australia and France. Directly relates to potential alcohol yield at approximately 1:1 by volume.",
    plain: "Australia's version of Brix. Same idea (measuring sugar), different scale. 1 degree Baumé = about 1% alcohol in the finished wine.",
    why: "You'll see Baumé quoted on Aussie sites way more than Brix. Same info, different unit.",
    when: "Pre-harvest sampling and ferment tracking on Australian wineries.",
    ruleOfThumb: "1°Bé ≈ 1.8°Bx · 1°Bé ≈ 1.0% v/v potential alcohol.",
  },
  {
    id: "sg",
    term: "Specific Gravity (SG)",
    category: "sugar-ferment",
    sop: "Ratio of the density of the wine/juice to the density of water at reference temperature. Measured by hydrometer or densitometer. Water = 1.000; grape juice starts approximately 1.080–1.110.",
    plain: "Cheap way to measure how dense the juice is. Water is 1.000. Juice starts around 1.100 (heavy with sugar) and finishes below 1.000 (dry) as yeast eats the sugar.",
    why: "Works in murky red ferments where a refractometer gets fooled by suspended solids.",
    when: "Ferment tracking, especially reds. SG below 1.000 = dry.",
    ruleOfThumb: "Every 10 SG points drop ≈ 1.3% v/v alcohol produced.",
  },
  {
    id: "yan",
    term: "YAN — Yeast Assimilable Nitrogen",
    category: "sugar-ferment",
    sop: "Sum of primary amino nitrogen (PAN, via formol titration) and NH₄⁺-N (via enzymatic assay or ion-selective electrode), expressed as mg/L N. Represents nitrogen forms metabolisable by Saccharomyces cerevisiae during fermentation.",
    plain: "The food yeast can actually eat. Not all nitrogen counts — it has to be a form the yeast can digest. Test the juice before you inoculate.",
    why: "Too little food = stuck ferment or a rotten-egg smell (H₂S). A cheap YAN test now saves a rescue restart later.",
    when: "Pre-inoculation on juice. Address any deficit at 1/3 sugar depletion, not later.",
    ruleOfThumb: "Target 150–250 mg/L. Below 140 mg/L = intervene.",
    cited: "Fugelsang & Edwards · Wine Microbiology, ch. 5",
  },
  {
    id: "dap",
    term: "DAP — Diammonium Phosphate",
    category: "sugar-ferment",
    sop: "Inorganic fermentation nutrient (NH₄)₂HPO₄. Delivers ammonium-N directly. Approximately 50 mg/L YAN uplift per 100 g/hL addition. Not to be used at inoculation — favours VA production and can promote spoilage flora.",
    plain: "Cheap, fast yeast food. Add it a third of the way through ferment (not at the start — that causes problems). 100 grams per hectolitre boosts YAN by about 50.",
    why: "The quickest fix when your juice is low on nitrogen. Just don't dump it in on day one.",
    when: "At 1/3 sugar depletion. Split into two doses if you need more than 40g/hL total.",
    ruleOfThumb: "100 g DAP / hL ≈ +50 mg/L YAN. Cap total N contribution around 40 g/hL.",
  },
  {
    id: "ferment-temp",
    term: "Fermentation temperature range",
    category: "sugar-ferment",
    sop: "Red fermentation typically 22–30°C for tannin and pigment extraction; white fermentation 12–18°C for thiol and ester preservation. Self-heating exotherm on batches ≥1000L requires active cooling to maintain setpoint.",
    plain: "Reds ferment warmer (helps pull out colour and structure). Whites ferment colder (keeps the fresh fruit smells intact). Big red ferments heat themselves up — you'll need to cool them.",
    why: "Wrong temperature = wrong style. Cool white ferment = crisp and aromatic. Hot red ferment = extractive and structured.",
    when: "Set at inoculation. Monitor daily during peak activity.",
    ruleOfThumb: "Whites <20°C to preserve thiols. Reds >25°C for tannin/colour extraction.",
  },
  {
    id: "stuck-ferment",
    term: "Stuck fermentation",
    category: "sugar-ferment",
    sop: "Cessation of yeast activity prior to sugar depletion. Diagnostic: flat SG over 48h with residual sugar > 5 g/L. Etiology includes YAN deficit, temperature excursion, ethanol shock, or micronutrient depletion.",
    plain: "The yeast quits before all the sugar is gone. Bad news — the wine's now vulnerable to spoilage. Find the cause fast: usually not enough food, wrong temperature, or the alcohol got too high for that yeast.",
    why: "Residual sugar + reduced SO₂ tolerance = wide-open spoilage window. Restart fast.",
    when: "Diagnose within 48h of a flat SG. Confirm YAN, temperature, and any inhibitors.",
    ruleOfThumb: "Restart with Uvaferm 43, rehydrated with GoFerm, step-fed 1:10 acclimation.",
    cited: "Lallemand · Stuck ferment restart protocol",
  },
  {
    id: "cap-mgmt",
    term: "Cap management — pumpover / punchdown / délestage",
    category: "sugar-ferment",
    sop: "Techniques for maintaining skin-juice contact during red fermentation. Pumpover: recirculation of juice over the skin cap. Punchdown (pigeage): mechanical submersion of the cap. Délestage: rack-and-return with full separation of juice and pomace.",
    plain: "You have to keep the grape skins mixed with the juice, or the wine ends up thin. Three ways: spray juice over the cap (gentle), punch it down (medium), or drain + return everything (aggressive).",
    why: "How you handle the cap decides how much colour, tannin and structure end up in the wine.",
    when: "Twice daily during peak ferment. Frequency drops as ferment slows.",
    ruleOfThumb: "Pinot: gentle punchdowns. Cabernet: pumpovers. Big Shiraz: délestage mid-ferment for structure.",
  },
  {
    id: "alcohol-tolerance",
    term: "Yeast alcohol tolerance",
    category: "sugar-ferment",
    sop: "Maximum ethanol concentration a given Saccharomyces strain can survive and continue fermenting through. Strain-specific; ranges from ~12% v/v (wild ferment average) to 18% v/v (fortified/late-harvest specialists).",
    plain: "Every yeast strain gives up at a different alcohol level. Some die at 12%, some push through 18%. Pick one that can finish the wine you're making with a safety margin.",
    why: "Choose wrong = stuck ferment. Simple as that.",
    when: "Strain selection stage, before inoculation.",
    ruleOfThumb: "EC1118: 18% · Uvaferm 43: 16% · D254: 14–15% · wild ferment: unpredictable.",
  },
  {
    id: "cold-soak",
    term: "Cold soak / pre-ferment maceration",
    category: "sugar-ferment",
    sop: "Extended aqueous maceration of crushed red must at 8–12°C for 3–7 days prior to inoculation. Purpose: aqueous extraction of anthocyanins and hydrophilic aroma precursors without ethanol-mediated tannin extraction.",
    plain: "Hold the crushed reds cold for a few days before starting the ferment. Water pulls out colour and fruit aromas without pulling out harsh tannins yet.",
    why: "Common tool for Pinot Noir. Adds colour and lift without heavy structure.",
    when: "Optional. Standard for Pinot Noir; used selectively for lighter reds.",
    ruleOfThumb: "SO₂ addition 24h before cold soak deters wild ferment and Brett during the hold.",
  },

  // ── ACID & pH (7) ─────────────────────────────────────────────────────
  {
    id: "ph",
    term: "pH (winemaking)",
    category: "acid-ph",
    sop: "Negative logarithm of hydrogen-ion activity in the wine matrix. Governs anthocyanin ionisation, SO₂ speciation, microbial thermodynamics, and enzymatic activity.",
    plain: "How acidic the wine is, on a log scale. Lower = more acidic. It's the single most important number in winemaking chemistry.",
    why: "pH controls SO₂ effectiveness, colour stability, and microbial safety. Two wines at the same SO₂ but different pH have wildly different protection.",
    when: "Every juice sample. Every ferment stage. Every pre-bottling check.",
    ruleOfThumb: "Reds: 3.4–3.7. Whites: 3.0–3.4. Above 3.6 = SO₂ efficacy craters.",
    cited: "Boulton et al · Principles & Practices of Winemaking, ch. 4",
  },
  {
    id: "ta",
    term: "TA — Titratable Acidity",
    category: "acid-ph",
    sop: "Total organic acid content in wine, determined by titration with standardised NaOH to endpoint pH 8.2 (Aus/US convention) or pH 7.0 (EU convention). Reported as g/L tartaric acid equivalent.",
    plain: "How much acid is in the wine total. pH tells you how *strong* it feels. TA tells you how *much* is there. They're not the same thing.",
    why: "TA drives mouthfeel and taste of freshness. pH drives chemistry. You need both numbers to know a wine.",
    when: "Every juice sample. Pre- and post-any acid adjustment.",
    ruleOfThumb: "Reds: 5.5–7 g/L. Whites: 6–8 g/L. Sparkling base: 8–10 g/L.",
  },
  {
    id: "va",
    term: "VA — Volatile Acidity",
    category: "acid-ph",
    sop: "Steam-distillable acid fraction, primarily acetic acid. Determined by cash still distillation or enzymatic assay. Independent from TA. Regulatory maximum typically 1.2 g/L (Aus/EU).",
    plain: "The vinegar smell. Small amount is normal. Above 0.7 g/L, you can smell it and the wine's got a problem — usually chronic Brett or bad bacteria.",
    why: "Above ~0.7 g/L it turns the wine towards vinegar. Legal ceiling stops your wine going to market at all.",
    when: "Test if you smell it. Test pre-bottling regardless. Test any suspected spoilage.",
    ruleOfThumb: "<0.4 g/L = clean · 0.4–0.7 = detectable · >0.7 = flaw territory.",
  },
  {
    id: "tartaric-malic",
    term: "Tartaric vs Malic acid",
    category: "acid-ph",
    sop: "Grape must contains two dominant organic acids. Tartaric acid: grape-endemic, resistant to bacterial degradation. Malic acid: metabolised by malolactic bacteria and depleted through respiration in warm climates.",
    plain: "Grape juice has two main acids. Tartaric is grape's own — stays put. Malic is sharper — it gets eaten by MLF bacteria or by heat during ripening. Cool climates keep more malic.",
    why: "How much malic is left tells you if MLF will work and how much softening it'll give you.",
    when: "Check on ripening samples. Confirm post-MLF via paper chromatography.",
    ruleOfThumb: "Cool climate juice: malic > 3 g/L. Warm climate: often < 1.5 g/L.",
  },
  {
    id: "buffering",
    term: "Buffering capacity",
    category: "acid-ph",
    sop: "The resistance of the wine matrix to pH change upon addition of acid or base. Governed by the concentration and pKa of weak acid/conjugate base pairs (primarily tartrate and organic acid buffers).",
    plain: "Some wines fight back when you add acid — the pH barely moves. Others shift easily. Always do a small-volume trial before dumping additions into a tank.",
    why: "Explains why 1 g/L of tartaric drops one wine 0.15 pH and another only 0.05 pH.",
    when: "Any acid adjustment. Any deacidification decision.",
    ruleOfThumb: "Bench-trial 100 mL before dosing the tank.",
  },
  {
    id: "acid-adjustment",
    term: "Acid adjustment",
    category: "acid-ph",
    sop: "Acidulation: addition of L-tartaric acid to lower pH and raise TA. Deacidification: addition of KHCO₃ or CaCO₃ to raise pH and lower TA. Pre-ferment additions preferred due to buffering advantage during active fermentation.",
    plain: "Adding tartaric acid lowers pH and adds tang. Adding potassium bicarbonate does the opposite. Best done pre-ferment — the yeast smooths it out.",
    why: "High-pH wines are microbially fragile and colour-thin. Adjustment protects long-term stability.",
    when: "Pre-ferment (best). Post-ferment if needed. Small trim only pre-bottling.",
    ruleOfThumb: "1 g/L tartaric ≈ +1.0 g/L TA. pH drop varies with buffering (~0.05–0.10 units).",
  },
  {
    id: "cold-stab",
    term: "Cold stabilisation",
    category: "acid-ph",
    sop: "Precipitation of potassium bitartrate (KHT) crystals via storage at −3 to −4°C for 7–14 days. Confirmed via conductivity delta or seeded mini-freeze test. Alternative technologies: electrodialysis, CMC addition, metatartaric acid.",
    plain: "Chill the wine to just above freezing for a week or two. Excess tartrate falls out as crystals. Rack it off before those crystals show up in the customer's glass.",
    why: "Consumers see crystals in-glass as a fault (they're not — but perception rules retail).",
    when: "Post-ferment, pre-bottling. Skip only if using CMC or electrodialysis.",
    ruleOfThumb: "Confirm stability with the conductivity or seed test before racking.",
  },

  // ── SO₂ & PRESERVATION (6) ────────────────────────────────────────────
  {
    id: "free-so2",
    term: "Free SO₂",
    category: "so2",
    sop: "The unbound sulfite fraction (SO₂ + HSO₃⁻ + SO₃²⁻) available for antimicrobial and antioxidant activity. Measured via aeration-oxidation, Ripper titration, or enzymatic assay.",
    plain: "The SO₂ that's actually doing work right now. The rest is spent. Keep this number where you need it based on your pH.",
    why: "Free SO₂ is what protects the wine. Bound SO₂ is already used up.",
    when: "Every 2–4 weeks in bulk storage. Pre-bottling confirmation 48h before.",
    ruleOfThumb: "Reds: 25–35 mg/L free. Whites: 30–45 mg/L free. Adjusted for pH via molecular target.",
  },
  {
    id: "bound-so2",
    term: "Bound SO₂",
    category: "so2",
    sop: "Sulfite that has undergone irreversible adduct formation with acetaldehyde, anthocyanins, sugars, and other electrophilic wine constituents. Not recoverable through normal cellar work.",
    plain: "SO₂ that already reacted with something in the wine and is used up. You can't get it back. Wines with lots of bound SO₂ demand more free SO₂ to compensate.",
    why: "Wines with high bound require higher additions to maintain molecular target.",
    when: "Assessed via Free vs Total SO₂ delta (Total − Free = Bound).",
    ruleOfThumb: "Bound climbs post-MLF and after oxidative events. Expect +20–40 mg/L addition to restore free.",
  },
  {
    id: "molecular-so2",
    term: "Molecular SO₂",
    category: "so2",
    sop: "The neutral aqueous SO₂ species (as opposed to bisulfite HSO₃⁻ or sulfite SO₃²⁻) responsible for antimicrobial activity. Fraction of free SO₂ present as molecular is pH-dependent per the Henderson-Hasselbalch equilibrium.",
    plain: "The version of SO₂ that actually kills yeast and bacteria. Depends heavily on pH. Same free SO₂ number can be great protection at low pH and useless at high pH.",
    why: "Free SO₂ alone tells you nothing without pH. Molecular is the number that matters.",
    when: "Calculate every time you set an SO₂ target. Use a chart or app.",
    ruleOfThumb: "Whites: 0.8 mg/L molecular target. Reds: 0.5 mg/L. Higher for Brett-risk wines.",
    cited: "Boulton et al · Principles & Practices of Winemaking, ch. 12",
  },
  {
    id: "so2-ph",
    term: "SO₂ effectiveness by pH",
    category: "so2",
    sop: "At pH 3.0, approximately 6% of free SO₂ exists in molecular form; at pH 3.6, only ~1%. A 0.6 pH unit differential thus represents a 6× swing in antimicrobial potency at identical free SO₂ concentration.",
    plain: "Every 0.1 pH higher, your SO₂ is about 25% weaker. Two wines with the same free SO₂ number can have wildly different protection based on pH alone.",
    why: "This is why 'just add 30 ppm SO₂' is a lazy answer without checking pH first.",
    when: "Any comparison of two wines. Any decision to skip a pH check.",
    ruleOfThumb: "Every 0.1 pH up = add ~5 mg/L free SO₂ to maintain molecular target.",
  },
  {
    id: "so2-legal",
    term: "Legal SO₂ limits",
    category: "so2",
    sop: "Total SO₂ regulatory ceilings vary by jurisdiction. Aus/NZ: 250 mg/L (dry) / 300 mg/L (sweet). EU: 150 mg/L (dry red) / 200 mg/L (dry white). USA: 350 mg/L. Organic certification bodies impose lower ceilings.",
    plain: "Every market has a legal cap. Go over it and you can't sell there. Organic and export specs are tighter than domestic conventional.",
    why: "Exceeding limits blocks export and triggers label recalls. Non-negotiable at commercial scale.",
    when: "Pre-bottling. Any export lot. Any organic-certified wine.",
    ruleOfThumb: "Aus: 250/300 · EU: 150/200 · USA: 350 · Organic Aus: 150.",
  },
  {
    id: "potassium-sorbate",
    term: "Potassium sorbate",
    category: "so2",
    sop: "Antifungal preservative (E202) used adjunctively with SO₂ in residual-sugar wines to inhibit yeast refermentation. Ineffective against lactic bacteria and forms geranium-off-note (2-ethoxyhexa-3,5-diene) in the presence of active LAB.",
    plain: "Extra insurance against the wine starting a second ferment in bottle. Only use in sweet wines. NEVER add if you have live lactic bacteria — creates a nasty geranium smell.",
    why: "SO₂ alone struggles to inhibit yeast in sweet wines. Sorbate closes that gap.",
    when: "Pre-bottling, only if residual sugar >4 g/L. Confirm MLF complete or blocked first.",
    ruleOfThumb: "150–200 mg/L. Never with active LAB. Confirm sterile-filter or full inhibition.",
  },

  // ── MALOLACTIC (4) ────────────────────────────────────────────────────
  {
    id: "mlf",
    term: "Malolactic fermentation (MLF)",
    category: "mlf",
    sop: "Bacterial decarboxylation of L-malic acid to L-lactic acid + CO₂ mediated primarily by Oenococcus oeni. Reduces titratable acidity ~2 g/L; softens perceived acidity; contributes diacetyl and buttery volatiles.",
    plain: "Bacteria (not yeast) convert sharp malic acid into softer lactic acid. Softens the wine's edge. Standard for most reds and oaked Chardonnay. Suppress it in aromatic whites.",
    why: "Softens acid, adds buttery notes, and stabilises the wine against later bacterial mischief.",
    when: "Post-primary ferment for most reds and oaked whites. Blocked for aromatics.",
    ruleOfThumb: "Confirm complete via paper chromatography: no malic spot = done. Then SO₂ to lock.",
    cited: "AWRI · MLF technical bulletin",
  },
  {
    id: "oenococcus",
    term: "Oenococcus oeni",
    category: "mlf",
    sop: "Gram-positive, catalase-negative, heterofermentative lactic acid bacterium. Tolerant of ethanol (up to 15% v/v), low pH (3.2+), and moderate SO₂ (bound tolerance up to 40 mg/L). Commercial preparations available as freeze-dried or liquid starter cultures.",
    plain: "The friendly bacteria that runs MLF. Tough — survives low pH, decent alcohol, and some SO₂. Buy a commercial strain; wild MLF is a gamble.",
    why: "Commercial strains give predictable MLF without the off-flavours wild lactics can throw.",
    when: "Inoculate at end of primary ferment (co-inoc) or when SG stabilises near 1.000.",
    ruleOfThumb: "Optimal: 18–22°C, pH 3.3–3.7, alcohol <14.5%, free SO₂ <15 mg/L.",
  },
  {
    id: "diacetyl",
    term: "Diacetyl",
    category: "mlf",
    sop: "2,3-butanedione. Vicinal diketone produced during MLF via citrate metabolism. Sensory threshold ~0.2 mg/L; peaks at 2–4 mg/L then declines via yeast reduction to acetoin.",
    plain: "That buttery smell in Chardonnay comes from this. Grows during MLF, then fades if you leave the wine on the lees. Wanted in Chardonnay; unwanted in reds.",
    why: "Signature of Chardonnay style. Warning flag in reds where fruit clarity is preferred.",
    when: "Monitor sensory through and post-MLF. Pump over with air to knock it back if too high.",
    ruleOfThumb: "Lean Chardonnay: stop MLF at 30–50%. Buttery Chardonnay: full MLF + extended lees.",
  },
  {
    id: "mlf-inhibit",
    term: "MLF inhibition (blocking)",
    category: "mlf",
    sop: "Prevention of malolactic activity via multiple pathways: pH depression <3.2, molecular SO₂ >0.8 mg/L (free >30 mg/L at typical pH), temperature <15°C, or enzymatic disruption via lysozyme (250–500 mg/L) or chitosan.",
    plain: "How to stop MLF from happening. Aromatic whites lose too much aroma if they go through MLF. Sweet wines can get bacterial spoilage. Block it with pH, SO₂, cold, or lysozyme.",
    why: "Aromatic whites (Riesling, SB) lose too much aroma. Sweet wines invite VA if left open.",
    when: "Immediately post-primary ferment. Waiting invites uninvited MLF.",
    ruleOfThumb: "Lysozyme 250–500 mg/L (fast). SO₂ + pH (passive). Cold (temporary).",
  },

  // ── OAK & AGING (5) ───────────────────────────────────────────────────
  {
    id: "oak-types",
    term: "Oak types — French / American / Hungarian",
    category: "oak-aging",
    sop: "Cooperage species: Quercus robur / Quercus petraea (French, tight grain, subtle spice, elevated extractable tannin). Quercus alba (American, loose grain, elevated cis- and trans-methyl-γ-octalactone giving coconut/vanilla). Quercus petraea (Hungarian, French-analogue at reduced cost).",
    plain: "French oak: subtle, spicy, expensive. American oak: sweet, coconut, vanilla, cheaper. Hungarian: French-like flavour at Hungarian prices. Choose based on the wine's style and your budget.",
    why: "Oak choice is a stylistic and financial decision. Wood chemistry drives flavour.",
    when: "Species selected at cooperage order. Match to variety and target style.",
    ruleOfThumb: "Pinot/Chardonnay: French. Bold bourbon-style reds: American. Volume Cab: Hungarian or blend.",
  },
  {
    id: "toast-levels",
    term: "Toasting levels",
    category: "oak-aging",
    sop: "Coopering process wherein barrel interior is exposed to controlled radiant heat, modifying lignin and cellulose degradation products. Toast levels — Light (L), Medium (M), Medium+ (M+), Heavy (H), Heavy Toast (HT) — control vanillin, guaiacol, furfural, and lactone profiles.",
    plain: "How much the cooper burned the inside of the barrel. Light = vanilla. Medium = coconut and toast. Heavy = coffee, smoke. Different levels change the flavour you get from the barrel.",
    why: "Toast controls vanillin, coconut lactones, coffee/smoke, and clove balance.",
    when: "Barrel purchase decision. Blend toast levels within a program for complexity.",
    ruleOfThumb: "M (Medium): universal. M+: fruit-forward reds. H: oxidative whites, ripe reds. HT: rare — smoke risk.",
  },
  {
    id: "oak-alternatives",
    term: "Oak alternatives — chips / staves / cubes / dust",
    category: "oak-aging",
    sop: "Non-barrel oak formats providing extractable phenolics and aromatics. Chips: <10 mm, rapid extraction. Staves: rack-mounted planks, sustained release. Cubes: intermediate kinetics. Dust: fining and blending.",
    plain: "Barrel wood in cheaper shapes. Chips work fast. Staves work slow. Cubes are in the middle. All of them give you 60–80% of barrel character at 10% of the cost.",
    why: "Barrels cost $800–1,800 each. Alternatives free budget for other winemaking priorities.",
    when: "Cost-conscious commercial wines. Volume programs. Stylistic infill.",
    ruleOfThumb: "Chips: 2–4 g/L, 4–8 weeks. Staves: 3–6 per barrel-equivalent, 8–16 weeks.",
  },
  {
    id: "mox",
    term: "Micro-oxygenation (MOx)",
    category: "oak-aging",
    sop: "Controlled dosing of gaseous oxygen into wine matrix at ~1–5 mL/L/month. Accelerates tannin polymerisation and colour stabilisation. Requires close monitoring of dissolved oxygen, VA, and Brettanomyces activity.",
    plain: "Feed the wine tiny bubbles of oxygen. Speeds up what barrel aging does naturally — softens tannin, stabilises colour. Overdo it and you get oxidation.",
    why: "Delivers barrel-aging results in months instead of years. But it's a skill — over-dosing kills the wine.",
    when: "Reds, post-ferment through pre-bottling.",
    ruleOfThumb: "Start 1–2 mL/L/month, taper down. Watch VA and Brett aggressively.",
  },
  {
    id: "extraction",
    term: "Extraction dynamics",
    category: "oak-aging",
    sop: "Solubilisation of grape-solid compounds into the fermenting matrix. Anthocyanins (aqueous-soluble) extract early. Tannins (ethanol-soluble) extract in mid-to-late ferment. Seed tannin extraction accelerates post-dryness at high ethanol.",
    plain: "Colour comes out early in ferment. Soft tannins come out in the middle. Harsh seed tannins come out at the end. Time your pressing based on which stage you want to lock in.",
    why: "Knowing extraction curves = knowing when to press. Too early = thin. Too late = harsh.",
    when: "Cap management + press timing — two big decisions per red batch.",
    ruleOfThumb: "Colour peaks mid-ferment; tannin continues post-ferment. Press between 0 and +5°Bx for balance.",
  },

  // ── FAULTS (6) ────────────────────────────────────────────────────────
  {
    id: "brett",
    term: "Brettanomyces (Brett)",
    category: "faults",
    sop: "Brettanomyces bruxellensis — spoilage yeast producing 4-ethylphenol (barnyard, sensory threshold ~600 μg/L) and 4-ethylguaiacol (smoky/bacon, ~110 μg/L). Establishes chronic infection in wood, requires molecular SO₂ maintenance >0.6 mg/L for control.",
    plain: "Wild yeast that lives in barrels and stinks the wine up with barnyard and bacon smells. Once it's in your cellar, it's hell to get rid of. Prevention (SO₂, sanitation, cool cellar) is everything.",
    why: "Chronic Brett kills fruit clarity and drives VA up over time.",
    when: "Highest risk: dry reds in barrel, warm cellars, low free SO₂.",
    ruleOfThumb: "Maintain molecular SO₂ ≥0.5 mg/L, cellar <18°C, sanitise between vintages.",
    cited: "Fugelsang & Edwards · Wine Microbiology, ch. 6",
  },
  {
    id: "reduction",
    term: "Reduction — H₂S / mercaptans",
    category: "faults",
    sop: "Volatile sulfur compounds (VSCs) formed via yeast metabolism under nitrogen limitation or extended lees contact. Species include H₂S (rotten egg, threshold ~50 μg/L), ethanethiol (garlic, ~1 μg/L), methanethiol (matchstick).",
    plain: "Smells like rotten eggs, garlic, or struck matches. Caused by stressed yeast or too much time on lees. Sometimes it's a stylistic choice; usually it's a problem. Test with a copper coin — if the smell lifts, copper fining will work.",
    why: "Can be a fault (blocked fruit) or a stylistic choice (matchstick in white Burgundy).",
    when: "At racking, pre-bottling. Copper coin test: if the smell lifts, copper will work.",
    ruleOfThumb: "Aerate first. If persistent: copper sulfate 0.2–0.5 mg/L (Cu). Bench-trial mandatory.",
  },
  {
    id: "oxidation",
    term: "Oxidation",
    category: "faults",
    sop: "Cumulative degradation via O₂ exposure. Manifests as browning (phenolic oxidation), prune/sherry aldehyde notes, and loss of primary fruit character. Dissolved oxygen target: <0.6 mg/L bulk; <1.0 mg/L at bottling.",
    plain: "The wine got too much air. Turns brown, tastes like sherry or dried fruit, loses freshness. Every open valve, every headspace, every pump-over adds to it. You can't reverse it — only prevent it.",
    why: "Every headspace, every open valve is a cumulative loss. Impossible to reverse.",
    when: "Prevention: manage headspace, inert-gas cover (N₂/Ar), maintain SO₂.",
    ruleOfThumb: "DO <0.6 mg/L bulk. DO <1.0 mg/L at bottling. Above 2 = red flag.",
  },
  {
    id: "tca",
    term: "Cork taint (TCA)",
    category: "faults",
    sop: "2,4,6-trichloroanisole. Chlorophenol-derived off-compound bio-methylated in cork substrate. Sensory threshold ~2 ng/L (parts per trillion). Not degradable; adsorbs onto pallets, cardboard, and cellar surfaces.",
    plain: "The wet cardboard smell that ruins a bottle. Detectable at parts per trillion — one contaminated bottle is enough for anyone to notice. Screw caps eliminate the risk almost entirely.",
    why: "Blindsides a whole cellar quickly — TCA is airborne and clings to cardboard and wood.",
    when: "Any 'off' bottle. Any suspect batch. Spot checks on cork closure lines.",
    ruleOfThumb: "3–5% of natural cork closures show detectable TCA. Screw caps ~0%.",
  },
  {
    id: "mousiness",
    term: "Mousiness",
    category: "faults",
    sop: "Palate-only fault from tetrahydropyridines (2-acetyl-tetrahydropyridine most common). Produced by lactic acid bacteria or Brettanomyces at low free SO₂. Undetectable on nose; presents on the palate as a lingering acrid aftertaste, often several seconds after the swallow.",
    plain: "You can't smell it — you taste it. A weird acrid aftertaste that shows up 5–10 seconds after the sip. Comes from lactic bacteria or Brett when SO₂ is low. Taste, don't just sniff.",
    why: "Under-appreciated because it's tasted, not smelled — a blind spot for nose-only tasters.",
    when: "Taste every wine post-MLF. Or add a drop of pH-8 buffer to lift the compound.",
    ruleOfThumb: "SO₂ + pH control prevents. Once present, no reliable remediation.",
  },
  {
    id: "refermentation",
    term: "Refermentation in bottle",
    category: "faults",
    sop: "Renewed fermentation activity post-bottling driven by residual fermentable sugar in presence of viable yeast. Results in CO₂ pressurisation, cork ejection, or bottle failure. Prevention requires either dryness (<2 g/L RS), sterile filtration (≤0.45 μm), or synergistic SO₂ + sorbate stabilisation.",
    plain: "The wine starts fermenting again in the bottle. CO₂ builds, corks push out, bottles explode. Only way to prevent: get it dry, sterile-filter it, or preserve properly with SO₂ + sorbate. Verify with more than one method.",
    why: "Small oversights compound: unfinished ferment + weak SO₂ + no filtration + warm storage = disaster.",
    when: "Any wine >4 g/L RS not sterile-filtered or preserved.",
    ruleOfThumb: "Sterile filter (0.45 μm) OR full dryness OR sorbate + adequate SO₂. Pick one, verify twice.",
  },

  // ── SENSORY & FLAVOUR (4) ─────────────────────────────────────────────
  {
    id: "diacetyl-sensory",
    term: "Diacetyl → buttery",
    category: "sensory",
    sop: "2,3-butanedione. Vicinal diketone from lactic bacterial citrate metabolism. Threshold ~0.2 mg/L; buttery / popcorn / butterscotch descriptors above threshold.",
    plain: "Butter and popcorn smell. Comes from MLF. Signature of oaked Chardonnay. If you smell it in a red, something's wrong.",
    why: "Buttery notes signal Chardonnay MLF. Popping up in reds = warning.",
    when: "Sensory panel post-MLF. Threshold ~0.2 mg/L.",
  },
  {
    id: "esters",
    term: "Esters → fruity",
    category: "sensory",
    sop: "Acid-alcohol condensation products from yeast metabolism. Isoamyl acetate → banana. Ethyl hexanoate → apple/pineapple. Ethyl butyrate → strawberry. Peak concentration at ferment end; hydrolyse over 6–18 months in bottle.",
    plain: "Fresh fruit smells in young wines — banana, apple, strawberry. Yeast makes them during ferment. They fade over the first year in bottle, so young-drinking wines aim to maximise them.",
    why: "The fresh fruit character of young whites and light reds. Fades within 6–18 months.",
    when: "Maximised via cool ferment + ester-forward yeast (VL3, X5).",
  },
  {
    id: "pyrazines",
    term: "Pyrazines → green pepper",
    category: "sensory",
    sop: "Methoxypyrazines. IBMP (isobutyl methoxypyrazine) most abundant. Aroma of capsicum, green pepper, cut grass. Concentrations inversely correlated with grape ripeness and sun exposure.",
    plain: "Green pepper and capsicum smells. Signature of Sauvignon Blanc; a fault in under-ripe Cabernet. Cool climates and less sun exposure keep more pyrazine.",
    why: "Cool-climate signature. Tracks inversely with ripeness — hang time reduces pyrazine.",
    when: "Sensory check at ripening. Blend or hang longer if pyrazine dominates.",
    ruleOfThumb: "SB threshold ~2 ng/L. Cabernet: >15 ng/L = green fault.",
  },
  {
    id: "rotundone",
    term: "Rotundone → peppery",
    category: "sensory",
    sop: "Sesquiterpene ((-)-rotundone). Aroma of freshly ground black pepper. Genetic olfactory polymorphism at OR7D4 renders ~50% of the tasting population anosmic to it.",
    plain: "The black pepper smell in cool-climate Shiraz. About half of humans can't smell it — genetic. If you can't detect pepper in Grampians Shiraz, that's you, not the wine.",
    why: "Signature of cool-climate Shiraz (Grampians, Canberra). Can't be added — only preserved.",
    when: "Handling matters: avoid pumping over with air; keep ferment temps moderate.",
    ruleOfThumb: "Half the tasting population can't detect it — polymorphism at OR7D4.",
  },

  // ── REGIONS & CLIMATE (5) ─────────────────────────────────────────────
  {
    id: "climate",
    term: "Cool vs warm climate viticulture",
    category: "regions",
    sop: "Growing-Season Temperature (GST) classification per Jones et al: cool <17°C, moderate 17–19°C, warm 19–21°C, hot >21°C. GST correlates with variety suitability, ripening potential, and stylistic tendencies.",
    plain: "Cool regions ripen grapes slowly, keeping fresh acid. Warm regions ripen fast, keeping more sugar and fruit. Same grape variety tastes wildly different in each — Chardonnay in Yarra vs Napa vs Marlborough are three different wines.",
    why: "Determines variety suitability, style tendencies, and ripening risk.",
    when: "Site selection. Variety matching. Ripening decisions.",
    ruleOfThumb: "Cool: retained acid, esters, ripening risk. Warm: alcohol, ripe fruit, ripening surety.",
  },
  {
    id: "terroir",
    term: "Terroir",
    category: "regions",
    sop: "Working definition: the interaction of physical (soil, aspect, elevation, mesoclimate), biological (rootstock, clone, canopy), and human (tradition, decisions) factors that yield site-specific wine expression. Not a mystical property; a shorthand for compound decisions.",
    plain: "The combination of soil, climate, slope, and choices that make one vineyard produce different wine than the neighbour's. Not magic — just a lot of specifics under one word.",
    why: "Explains why the same variety, vinified similarly, tastes different across parcels 100m apart.",
    when: "Vineyard planning, single-vineyard designations, marketing narrative.",
    ruleOfThumb: "Soil + aspect + microclimate dominate. Marketing loves mystery; winemakers should love specifics.",
  },
  {
    id: "bordeaux",
    term: "Bordeaux — blends and style",
    category: "regions",
    sop: "Left Bank (Médoc, Graves) — Cabernet Sauvignon dominant, gravel-derived soils, structured tannin. Right Bank (Saint-Émilion, Pomerol) — Merlot dominant, clay/limestone, plusher tannin architecture. Historical reference for Bordeaux-style blend construction.",
    plain: "Bordeaux has two sides. Left Bank is Cabernet-dominant, structured, ages long. Right Bank is Merlot-led, softer, drinks earlier. Almost every 'Bordeaux blend' anywhere in the world is one style or the other.",
    why: "Global reference for red blends. Australian analogues: Coonawarra, Margaret River, Yarra.",
    when: "Blend architecture decisions. Understanding the reference for structured reds.",
    ruleOfThumb: "Cab-Merlot 60/40 to 80/20 typical. Petit Verdot 3–5% for lift. Cab Franc for perfume.",
  },
  {
    id: "barossa",
    term: "Barossa Valley (South Australia)",
    category: "regions",
    sop: "Warm-Mediterranean South Australian region, established 1840s. Signature Shiraz on ancient own-rooted vines (many 100+ years). Grenache and Cabernet Sauvignon supporting. GST ~20°C, aspect-dependent site selection critical.",
    plain: "Old Australian region, hot climate, home of big Shiraz on very old vines. Barossa reds are famous for dense, ripe, structured styles — and 100+ year old vines are almost unique in the wine world.",
    why: "One of the oldest continuously-producing regions globally. Vine age is defining.",
    when: "Reference for old-vine, ripe, oaked reds. Contrast with cool-climate Shiraz.",
    ruleOfThumb: "Old-vine Shiraz: dense, savoury, black-fruited. Grenache: bright, moderate structure.",
  },
  {
    id: "hunter",
    term: "Hunter Valley (New South Wales)",
    category: "regions",
    sop: "Australia's oldest continuously producing wine region (established 1820s). Warm humid subtropical climate; ripening pressure from January-February rainfall risk. Signature: unoaked Semillon (10–11% ABV, taut acid, decade-plus ageing curve) and earthy Shiraz.",
    plain: "Australia's oldest wine region — up in NSW. Hot and humid, so rain at harvest is a constant threat. Famous for a Semillon style found nowhere else — low alcohol, sharp acid, ages 10+ years into honey. Pokolbin is the heart of it.",
    why: "The Hunter Semillon style has no true global parallel — a genuine Australian idiom.",
    when: "Reference for aged unoaked whites and earthy/savoury Shiraz styles.",
    ruleOfThumb: "Pokolbin sub-region: heart of the Hunter. Vintage highly variable.",
  },

  // ── PAIRING PRINCIPLES (3) ────────────────────────────────────────────
  {
    id: "tannin-protein",
    term: "Tannin + protein pairing",
    category: "pairing",
    sop: "Protein-tannin binding: dietary proteins (particularly muscle collagen, casein) form insoluble complexes with polyphenolic tannins in the oral cavity, reducing perceived astringency. Underpins the classic red-wine-with-red-meat pairing.",
    plain: "Tannin grips protein. So a tannic wine feels smoother with steak than on its own. That's why Cabernet works with beef and falls flat with a salad.",
    why: "Explains why steak works with Cabernet and the same wine falls flat with a light salad.",
    when: "Any red-wine pairing decision.",
    ruleOfThumb: "Higher tannin → fattier / protein-forward dish. Pinot with duck. Cabernet with beef.",
  },
  {
    id: "acid-fat",
    term: "Acid + fat pairing",
    category: "pairing",
    sop: "Acid-mediated palate cleansing: acidic wines cut lipid film on the palate, refreshing between bites of fatty food. Independent of wine colour; drives Champagne with fried food and Riesling with pork belly.",
    plain: "Acidic wines cut through fat. Champagne with fried chicken. Sancerre with oysters. Riesling with pork belly. When food is rich, reach for something with brisk acid.",
    why: "One of the most reliable food/wine principles. Works across cuisines.",
    when: "Any dish where the fat sits heavy on the palate.",
    ruleOfThumb: "Higher fat → higher-acid wine.",
  },
  {
    id: "sweetness-match",
    term: "Sweetness matching",
    category: "pairing",
    sop: "Perceived sweetness parity: the wine's residual sugar must equal or exceed that of the dessert, or the wine will read as bitter/tart against the sweeter reference. Most-broken pairing principle in on-premise service.",
    plain: "Your dessert wine has to be at least as sweet as the dessert. Otherwise the wine feels thin and sour next to the food. Ordering Sauternes with a lemon tart doesn't work — the tart is sweeter.",
    why: "Most-broken pairing rule in restaurants.",
    when: "Any dessert course.",
    ruleOfThumb: "Chocolate = fortified sweet (PX, Rutherglen Muscat). Tart = late-harvest Riesling.",
  },

  // ── CONSULTANT'S TOOLKIT — Deck 3 · sales & client conversations (15) ─
  // For Rich's sales calls. SOP = what to actually SAY on the call.
  // Plain = the underlying idea in his head. Written to be scanned mid-call.
  {
    id: "cons-elevator",
    term: "Elevator pitch — what Ownology does",
    category: "consulting",
    sop: "Cellar intelligence for boutique winemakers. Conversational AI grounded in the oenology reference corpus (Zoecklein, Boulton, Ribéreau-Gayon, AWRI). Every answer cited. SOPs editable. APCO drafting built in. Priced from $22/mo — no per-user fees, no implementation consultant.",
    plain: "It's software that lets you ask cellar questions and get answers with citations. Keeps your SOPs current, handles compliance drafting. Under a hundred bucks a month. Winemaker AI, priced for actual winemakers.",
    why: "First 15 seconds of any call. If they don't get it here, nothing else lands.",
    when: "Cold outreach reply. First inbound demo request. Trade show conversations.",
    ruleOfThumb: "Say what it IS before what it DOES. Category first, feature list never.",
  },
  {
    id: "cons-hallucination",
    term: "\"Is the AI going to lie to me?\"",
    category: "consulting",
    sop: "Retrieval-augmented generation on a curated oenology corpus. Owen returns citations per answer. On out-of-corpus questions, Owen refuses rather than fabricates. Not a general-purpose chatbot fine-tuned on winemaking — a purpose-built retrieval layer over reference material we own.",
    plain: "Every answer shows where it came from. If Owen doesn't know, he says so. That's the con·science bit — not internet CON, backed IN SCIENCE. You get the receipts, not just the answer.",
    why: "This is THE objection. Winemakers have been burned by ChatGPT confidently making things up.",
    when: "Any prospect who's tried general-purpose AI and got bad advice.",
    ruleOfThumb: "Show, don't tell — pull up /learn or ask Owen a live question mid-call.",
  },
  {
    id: "cons-vs-innovint",
    term: "\"How is this different from InnoVint / Vintrace?\"",
    category: "consulting",
    sop: "Same category (cellar intelligence software). Different DNA. Boutique-priced (~10% of enterprise incumbents on loaded cost). No per-user fees. No implementation consultant required. Conversational AI is native, not bolted on. Built by working winemakers, not by a software company that acquired a wine domain.",
    plain: "Same job, one-tenth the price. Full receipts on our /pricing-comparison page. They're built for wineries with a CFO. We're built for wineries with a founder still on the crush pad.",
    why: "The prospect has almost certainly priced or been quoted by one of them. This must be a confident answer.",
    when: "Any commercial-scale prospect. Any prospect who mentions competitor names.",
    ruleOfThumb: "Send them /pricing-comparison after the call. It's your receipt.",
    cited: "See /pricing-comparison for the full math.",
  },
  {
    id: "cons-data-privacy",
    term: "\"Where does my data go? Is it safe?\"",
    category: "consulting",
    sop: "SOPs and vintage records stored in customer-scoped account with encryption in transit and at rest. Not used to train foundation models. Full data portability on cancellation — CSV export of all user-generated content. Right to delete honoured immediately.",
    plain: "Your data stays in your account. We don't feed it to AI training. You can export it or delete it any time. Yours forever. That's the third pillar on our homepage — 'your data stays yours' — and we mean it.",
    why: "Every winery has a competitor they don't want reading their notebook. Legitimate concern.",
    when: "Any winery with proprietary style or long history to protect.",
    ruleOfThumb: "Point them at the third Why Ownology box on the homepage.",
  },
  {
    id: "cons-replaces-consultant",
    term: "\"Are you replacing my consultant?\"",
    category: "consulting",
    sop: "Complementary positioning, not replacement. Owen handles reference lookups, 3am chemistry questions, and SOP retrieval. Human consultants handle judgment calls: blend architecture, style trajectory, complex fault diagnosis, business strategy. Different jobs.",
    plain: "No. Consultants make judgment calls. Owen answers the questions you'd otherwise Google or dig through a textbook for. Two different jobs. Best-case scenario, your consultant loves us because you stop asking them what SO₂ target to hit.",
    why: "Prospects who work with consultants are cautious about anything that might undercut a trusted relationship.",
    when: "Prospects with an existing consultant relationship. Sommeliers moonlighting as consultants.",
    ruleOfThumb: "Never position AI as replacing humans. Position it as freeing humans for the hard problems.",
  },
  {
    id: "cons-import-story",
    term: "\"How do I get my history into it?\"",
    category: "consulting",
    sop: "/import surface handles five modalities: voice memo transcription (Whisper), camera OCR for notebook photos (Claude Sonnet vision), clipboard paste with image OCR + spell-check, structured CSV upload with column mapping, and bulk folder drop with per-file confidence grading (image / text / PDF / XLSX / WhatsApp export / audio).",
    plain: "Take a photo of your notebook. Drop a folder of PDFs. Paste a screenshot. It reads them all, structures the data, you review and save. Not a week-long onboarding — a single afternoon.",
    why: "Migration friction is the #1 reason winemakers stay on paper. Kill the friction, kill the resistance.",
    when: "Any prospect currently on Excel / paper / whiteboards / WhatsApp threads.",
    ruleOfThumb: "Offer to sit with them for one hour of import — they'll close on the call.",
  },
  {
    id: "cons-pricing-talk",
    term: "Pricing conversation",
    category: "consulting",
    sop: "Four tiers, monthly on annual: Free Run $0 (unlimited AI questions, no SOPs) · Cellar Hand $22/mo (starter commercial + serious DIY) · The Press $44/mo (typical boutique, full commercial toolkit) · The Vigneron $88/mo (owner-operator, 3 seats, vineyard scope, APCO). No per-user surcharges. No implementation cost.",
    plain: "Free tier for curious folks. $22 for starter. $44 for a typical winery. $88 for serious owner-operators. What's on the page is what you pay — no hidden fees.",
    why: "Sales confidence comes from clarity. Fumble this and you undermine the whole 10x-cheaper narrative.",
    when: "After they've indicated interest. Before they've asked (they always ask).",
    ruleOfThumb: "Say the numbers plainly. Don't apologise, don't over-explain, don't offer discounts on the first call.",
  },
  {
    id: "cons-who-is-owen",
    term: "\"Who is Owen? Is that a real person?\"",
    category: "consulting",
    sop: "Owen is the AI persona of Ownology — the cellar you can talk to. Not a mascot, not a stand-in for a real person. The face of the con·science layer: retrieval, citation, and honest refusal on out-of-corpus questions. Named to be conversational, not authoritative.",
    plain: "Owen is what we call the AI. Not a real person, not pretending to be one. Just a name for the thing you talk to — because 'ask the AI' sounds cold and 'ask Owen' feels like a colleague.",
    why: "Some prospects find AI personification off-putting. Have a straight answer ready.",
    when: "Any prospect who asks or looks confused. Small talk moments.",
    ruleOfThumb: "If they seem cold on the persona, drop the name and say 'the AI' — Owen is a wrapper, not a hill to die on.",
  },
  {
    id: "cons-ai-wrong",
    term: "\"What if the AI gives me bad advice on my ferment?\"",
    category: "consulting",
    sop: "Owen surfaces citations per answer. Recommended workflow: on any critical decision (SO₂ addition, ferment restart, blend commitment), verify the answer against the cited source before acting. Owen is decision-support, not decision-owner. Same posture as consulting a textbook.",
    plain: "Owen shows you the source. On critical calls, check the source, then YOU make the decision. Owen helps you think — he doesn't replace your judgement. Same way you'd cross-check a textbook before acting on it.",
    why: "Serious winemakers ask this. The answer must position Owen correctly — assistant, not oracle.",
    when: "Any winemaker who's been burned by a bad recommendation from any source.",
    ruleOfThumb: "Reassure by acknowledging Owen isn't infallible — that's why the citations exist.",
  },
  {
    id: "cons-sop-onboarding",
    term: "\"How does it learn my winery?\"",
    category: "consulting",
    sop: "Customer SOPs uploaded via /import are vector-embedded to the customer's scoped account. Retrieval combines the private customer corpus with the public oenology reference corpus. Where customer SOP overlaps with public reference, customer SOP takes precedence.",
    plain: "You upload your SOPs and Owen reads them. From that point, your SOPs override the default reference material. If your winery says 'we do it this way', Owen defaults to your way.",
    why: "Winemakers care about their SOPs being respected, not overwritten.",
    when: "Any prospect with mature SOPs — likely mid-size commercial or a consulting-heavy small winery.",
    ruleOfThumb: "'Your SOPs win' is a good tagline in these conversations.",
  },
  {
    id: "cons-team-access",
    term: "\"Can my whole team use it?\"",
    category: "consulting",
    sop: "Cellar Hand and The Press are single-account tiers. Vigneron includes 3 team seats. Enterprise custom quote for larger teams — no per-user surcharge, tier-based only.",
    plain: "Cellar Hand and The Press are for one winemaker. Vigneron includes 3 team logins. Bigger teams — talk to us, we'll quote flat rate. No per-user hidden fees like the other guys.",
    why: "Multi-user is where competitor pricing balloons — this is a differentiator worth naming.",
    when: "Any prospect with more than one person on the cellar floor.",
    ruleOfThumb: "Explicitly contrast: 'No per-user fees. Ever.'",
  },
  // ── Decision frameworks — the calls a consultant is asked to make ────
  {
    id: "cons-when-to-press",
    term: "When to press (reds)",
    category: "consulting",
    sop: "Press timing decision governed by extraction curve vs seed-tannin exposure. Standard window: 0 to +5°Bx for balanced structure. Earlier (+3 to +7°Bx) for lighter styles. Later (dry through -1°Bx) only when heavy structure desired; expect grippy tannins.",
    plain: "Press when the ferment's nearly dry — around zero Brix — for most reds. Earlier if you want a lighter style. Wait past dry only if you want heavier structure, and know you'll get grippy tannins.",
    why: "Press timing is a decision a consultant is asked to weigh in on constantly.",
    when: "Late in red ferment. Any prospect on a red-heavy program.",
    ruleOfThumb: "Taste + Brix + tannin bench trial. Never press on the calendar alone.",
  },
  {
    id: "cons-when-to-blend",
    term: "When to blend",
    category: "consulting",
    sop: "Structural blend decisions (variety ratio, Petit Verdot lift, Cab Franc perfume) — commit BEFORE oak. Stylistic blends (softening tannin, oak marker correction, integration) — commit AFTER oak. Triplicate 100 mL bench trial mandatory before any tank commit.",
    plain: "Big decisions about which grapes and what ratio — do them BEFORE the barrel. Small tuning blends — do them AFTER the barrel. Always test three small beakers before committing the tank.",
    why: "Blend timing decisions come up in every consultation. Frame is critical.",
    when: "Post-ferment onwards. Any prospect thinking about their first blended wine.",
    ruleOfThumb: "Triplicate bench trial or don't do it.",
  },
  {
    id: "cons-when-to-release",
    term: "When to hold vs release",
    category: "consulting",
    sop: "Release criterion: primary fruit + secondary (oak, MLF-derived) + tertiary (bottle age, integration) sit in balance without one dominating. Hold if primary fruit still masking structure. Hold if tannin still puckering. Release if primary fruit is fading faster than integration is arriving.",
    plain: "Sell it when it stops changing week-to-week. If you're still tasting sharp oak or grippy tannin at 6 months, give it more time. If the fruit's fading fast, ship it faster.",
    why: "Cellar economics question — every month of delay is capital tied up.",
    when: "Any winery with capital constraints and finished stock in bulk.",
    ruleOfThumb: "Blind-taste against a reference — your palate normalises to a single wine over time.",
  },
  {
    id: "cons-when-to-escalate",
    term: "When to escalate to a consultant (know the limit)",
    category: "consulting",
    sop: "Escalate to human consultant on: (1) fault chemistry unclear after basic diagnostics, (2) blend calls impacting >30% of program value, (3) regulatory / compliance questions with export implications, (4) VA trajectory adverse and unresponsive to standard interventions, (5) style pivot decisions on flagship wines.",
    plain: "Call a proper consultant when: you can't identify what's wrong, big blends touching a lot of your production, export/legal questions, VA that's getting worse not better, or when you're thinking of changing your flagship style.",
    why: "Knowing your limit is a consultant skill in itself. Rich needs to know when NOT to be the answer.",
    when: "Rich's own decision-making — when to stop giving advice and refer.",
    ruleOfThumb: "If you'd need to Google it twice to be confident — refer.",
  },

  // ── BUSINESS OF WINE — Deck 4 · commercial fluency (10) ──────────────
  // For Rich to be conversant on the money side of a winery. Not deep
  // accounting — the concepts a consultant should be able to speak to.
  {
    id: "biz-cogs",
    term: "COGS — Cost of Goods Sold",
    category: "business",
    sop: "Direct cost per bottle: grape cost (fruit purchase or vineyard amortisation), production labour, packaging (bottle, closure, capsule, label), oak amortisation per litre, freight to distributor. Excludes overhead, marketing, and cellar door.",
    plain: "What it actually costs to make one bottle before you've paid the rent or the marketing bill. Grapes, labour, glass, cork, oak, and getting it to the warehouse.",
    why: "Sets your minimum sustainable price. If your wholesale price is below 3× COGS, you're subsidising the drinker.",
    when: "Every new SKU decision. Every vintage cost review.",
    ruleOfThumb: "Boutique red bottle COGS: $8–15. Boutique premium: $18–30. Ultra: $40+. Wholesale = 3× COGS floor.",
  },
  {
    id: "biz-margin-stack",
    term: "The three-tier margin stack",
    category: "business",
    sop: "Producer → Distributor → Retailer margin stack. Producer wholesale price (ex-GST). Distributor takes 25–35%. Retailer takes 30–40%. RRP typically 2.4–3.2× wholesale price ex-GST.",
    plain: "A wine that leaves your cellar at $20 sits on a shelf at $50–60. That's not gouging — that's the middle-tier reality. You have to price for THAT shelf number, not for what you'd like to charge.",
    why: "Underpricing at wholesale wrecks your shelf position. Overpricing kills volume.",
    when: "Every price decision. Every distribution conversation.",
    ruleOfThumb: "Aim shelf-price backwards: RRP ÷ 2.8 = wholesale. Wholesale ÷ 3 = COGS ceiling.",
  },
  {
    id: "biz-dtc-vs-trade",
    term: "DTC vs Trade — the strategic split",
    category: "business",
    sop: "Direct-to-Consumer (DTC): cellar door, wine club, e-commerce. Higher margin (retail-equivalent to producer), owned customer relationship, capped scale. Trade: distributor + retail, higher volume, lower margin per bottle, ceded relationship. Most sustainable boutiques run 40–60% DTC.",
    plain: "DTC is where you make money per bottle but can only sell so many. Trade is where you move volume but the margin bleeds. Most healthy boutiques are 40–60% DTC — enough scale from trade, enough margin from DTC.",
    why: "The mix determines whether you're a hobbyist or a viable business.",
    when: "Every strategic review. Every conversation about growth mode.",
    ruleOfThumb: "Under 30% DTC → cash squeeze. Over 70% DTC → growth capped by cellar door foot-traffic.",
  },
  {
    id: "biz-cellar-door",
    term: "Cellar door economics",
    category: "business",
    sop: "Revenue drivers: tasting fees (redeemable / retained), bottle sales conversion (typical 60–75% of walk-ins buy), club conversion (10–20% of tastings), average dollar transaction (varies from $30 casual to $200+ for premium regions). Cost drivers: hosting staff, tasting inventory (2–4% of tasting flight cost), facility.",
    plain: "The cellar door is your most profitable channel per bottle. Real numbers: two-thirds of visitors buy something, one in seven joins a club, average spend $80–150. But every visitor costs you staff hours and open bottles — track it.",
    why: "Cellar door is where DTC lives or dies. Also where the con·science of your brand is felt directly.",
    when: "Any conversation about growth, staffing, or DTC strategy.",
    ruleOfThumb: "Break-even at ~40 visitors/day for a $10 tasting fee model with 1 host. Better with a $25 elevated fee.",
  },
  {
    id: "biz-wine-club",
    term: "Wine club economics",
    category: "business",
    sop: "Subscription-based DTC. Typical structure: quarterly release, 2–6 bottles per shipment. Member LTV drives economics — churn rate targeting <20% annually. Acquisition cost paid back over 3–5 shipments. Members typically buy 2–3× their subscription volume over a year.",
    plain: "Wine clubs = recurring revenue. Get someone signed up, they stay 4-5 years on average, and buy way more than their subscription. Losing them = losing three years of margin. Fight churn like your life depends on it.",
    why: "Predictable revenue, high LTV, insulates against retail volatility.",
    when: "Any DTC growth conversation. Any cellar door optimisation.",
    ruleOfThumb: "Target: club acquisition cost < 3× shipment value. Aim <15% annual churn.",
  },
  {
    id: "biz-apco",
    term: "APCO — Australian Packaging Covenant",
    category: "business",
    sop: "The Australian Packaging Covenant Organisation. Mandatory scheme for businesses using packaging in Australia with turnover >$5M or importing brand-owner status. Annual reporting on packaging materials, recyclability, and Sustainable Packaging Guidelines (SPG) targets by 2025/2030.",
    plain: "Australian rule that says if you put wine in a bottle and sell it, you have to report on your packaging every year and prove you're heading toward recyclable/reusable materials by 2025 and 2030 deadlines. Fines are real.",
    why: "Ownology has an APCO Assistant on the roadmap because this is a real winemaker headache. Consultants who understand APCO save wineries days of paperwork.",
    when: "Any winery >$5M turnover. Any conversation about compliance.",
    ruleOfThumb: "Report is due by 31 March each year for the previous calendar year. Late = penalty.",
  },
  {
    id: "biz-wet",
    term: "WET — Wine Equalisation Tax",
    category: "business",
    sop: "Australian federal tax of 29% on wholesale wine value. Producer rebate available for eligible producers up to $350k/year (proposed changes ongoing). Applies at the wholesale point in the three-tier chain.",
    plain: "Australian government takes 29% of wholesale wine sales as tax. There's a rebate up to $350k a year that keeps small producers alive. If you're helping a client price wine, WET is non-negotiable in the calculation.",
    why: "One of two big Australian wine taxes. Miss it in a costing conversation and you look amateur.",
    when: "Every pricing conversation with Australian producers.",
    ruleOfThumb: "Wholesale ex-GST × 1.29 = WET-inclusive wholesale. Rebate cap $350k/year per group.",
  },
  {
    id: "biz-liability",
    term: "Winery liability & liquor licensing",
    category: "business",
    sop: "Product liability insurance (contamination, injury) sits alongside RSA (Responsible Service of Alcohol) obligations. Australian state-specific liquor licensing (producer's, cellar door, retail) required at each channel. Public liability for cellar door visitor risk. Consult a specialist wine industry broker.",
    plain: "Winemaking is a regulated activity. You need product liability insurance in case someone gets sick, public liability for cellar door visitors, and state liquor licences for anywhere you sell. Get a wine-specialist broker — general business insurance will miss things.",
    why: "One breach can end a small winery. Consultants who know the surface area are trusted more.",
    when: "New winery setup. Any conversation about expanding to a new channel.",
    ruleOfThumb: "Wine-specialist brokers: WFI Wine Insurance, Cavill Wine Insurance. Not your mate's business broker.",
  },
  {
    id: "biz-vintage-yield",
    term: "Vintage yield economics",
    category: "business",
    sop: "Yield per hectare (t/ha) drives grape supply cost. Boutique premium sites: 4–7 t/ha (yield restricted for concentration). Volume regions: 12–20 t/ha. Grape cost varies from $2,000–3,500/t (bulk warm-climate) to $12,000+/t (premium single-site cool-climate Pinot).",
    plain: "How many tonnes of grapes come off a hectare of vineyard. Boutique wineries yield less (4–7 tonnes) because they keep quality up. Bulk regions get triple that. Grape cost per tonne swings 5× between bulk and premium — determines your COGS.",
    why: "Understanding yield economics helps you talk credibly to a grower or a boutique client.",
    when: "Any conversation about vineyard purchase, contracting, or grape sourcing.",
    ruleOfThumb: "6 t/ha × 750L per tonne × 1000 bottles per hL ≈ 4,500 bottles per hectare at premium sites.",
  },
  {
    id: "biz-cashflow",
    term: "Vintage cash cycle",
    category: "business",
    sop: "18–36 month cash conversion cycle: fruit paid at harvest (Feb–Apr), packaging paid at bottling (12–18 months post-harvest for reds), retail invoiced at delivery (typically 30–60 days terms), DTC realised over 6–24 months of release cycle. Working capital equivalent to 1–2 full vintages typical.",
    plain: "You pay for grapes in autumn, pay for bottles 18 months later, get paid by shops a month or two after delivery. If you're not sitting on cash equal to a year or two of production, one bad vintage kills you. It's why most boutique wineries eventually raise capital or partner up.",
    why: "The single biggest reason boutique wineries fold. Not bad wine — bad cash cycle understanding.",
    when: "Any founder considering scaling. Any consulting engagement on growth.",
    ruleOfThumb: "Working capital = 1.5× annual COGS is a defensible minimum for a growing boutique.",
  },

  // ── VINEYARD & VITICULTURE — Deck 2 · what happens before the cellar (20)
  // Rich flagged viticulture as a core learning goal. These cards cover the
  // decisions a grower makes that determine what the winemaker inherits.
  {
    id: "vit-aspect",
    term: "Aspect (slope orientation)",
    category: "viticulture",
    sop: "Compass orientation of a vineyard slope, determining diurnal sun exposure profile. Southern Hemisphere: north-facing = warmest (max sun), south-facing = coolest. Northern Hemisphere inverted.",
    plain: "Which way the vineyard slope faces. In Australia, north-facing slopes get the most sun — hottest, ripest fruit. South-facing = cooler, later-ripening, more acid retention.",
    why: "Aspect can shift ripening by 10–14 days across a single vineyard. Frost risk is aspect-dependent.",
    when: "Site selection. Understanding a producer's block-level style decisions.",
    ruleOfThumb: "Southern Hemisphere: N-facing = warm-climate style. S-facing = cool-climate style. On the SAME site.",
  },
  {
    id: "vit-soils",
    term: "Soil types — limestone / sand / clay / granite / terra rossa",
    category: "viticulture",
    sop: "Soil composition drives water-holding capacity, nutrient availability, and root penetration depth. Limestone: alkaline, drainage-plus-retention, structural elegance. Sand: fast-drain, vigour-limiting. Clay: retentive, rich, prone to over-vigour. Granite: acidic, mineral-driven. Terra rossa: iron-rich clay-over-limestone (Coonawarra signature).",
    plain: "The dirt matters. Limestone = elegance (Chablis, Coonawarra red terra rossa). Sand = leaner wines. Clay = big rich wines. Granite = mineral, structured. Each variety has soils it prefers.",
    why: "Explains why the same variety tastes different from one paddock to the next. Grape-buying decision-critical.",
    when: "Vineyard purchase, variety planting decisions, terroir conversations.",
    ruleOfThumb: "Cool-climate Chardonnay: limestone/chalk. Cabernet: gravel or terra rossa. Shiraz: broad tolerance.",
  },
  {
    id: "vit-water",
    term: "Water availability — dryland vs irrigated",
    category: "viticulture",
    sop: "Water regime: rainfed (dryland) reliant on annual precipitation vs supplemented irrigation. Australian premium regions largely irrigated (Barossa, McLaren Vale) due to <500mm growing-season rainfall. Deficit irrigation used strategically to concentrate berries.",
    plain: "Some vineyards get all their water from rain (dryland — mostly Europe). Most Australian premium vineyards need irrigation — but the smart ones underwater on purpose late in the season to concentrate flavour.",
    why: "Dryland vs irrigated changes vine physiology dramatically. Also cost / risk profile.",
    when: "Any conversation about vineyard purchase or vintage variation.",
    ruleOfThumb: "Deficit irrigation post-véraison → concentrated berries. Standard practice for premium Australian reds.",
  },
  {
    id: "vit-elevation",
    term: "Elevation & mesoclimate",
    category: "viticulture",
    sop: "Vineyard elevation modifies mesoclimate: mean temperature drops approximately 0.6°C per 100m of elevation gain. Higher elevation extends hang time, preserves acid, and reduces disease pressure via lower humidity.",
    plain: "Every 100 metres higher = about 0.6°C cooler. That's why Adelaide Hills sits above Barossa, why Grampians produces peppery Shiraz, why Alpine Valleys ripens later than the plains below.",
    why: "Explains why two regions 30km apart make radically different wines.",
    when: "Regional style conversations. Vineyard purchase.",
    ruleOfThumb: "Add 100m elevation ≈ subtract 1 week of ripening.",
  },
  {
    id: "vit-rootstock",
    term: "Rootstock selection",
    category: "viticulture",
    sop: "Grafted vine architecture: American Vitis rootstock (phylloxera-resistant) supports Vitis vinifera scion. Rootstock choice governs phylloxera resistance, drought tolerance, nematode resistance, and vigour. Common: 110R (drought), 1103P (universal), Ramsey (vigorous, nematode-resistant).",
    plain: "Modern vineyards are two vines joined together — a resistant American root system plus a European fruit-producing top. The root choice controls drought tolerance, nematode resistance, and vine vigour.",
    why: "Phylloxera destroyed Europe in the 1870s. Rootstock is the reason modern viticulture exists.",
    when: "New planting decisions. Any conversation about vine health or replanting.",
    ruleOfThumb: "110R: drought hard sites. 1103P: universal safe choice. Ramsey: high vigour + nematode risk.",
  },
  {
    id: "vit-clones",
    term: "Clonal selection",
    category: "viticulture",
    sop: "Genetic subvariants of a grape variety, propagated vegetatively from single-vine selections. Different clones express different berry size, aromatic profile, yield potential, and disease susceptibility within the same variety. Example: Pinot Noir 777 (Dijon, fruit-forward) vs MV6 (Australian heritage, structured).",
    plain: "Every grape variety has dozens of clones — genetic subversions with slightly different personalities. Same Pinot Noir grape, different clones give different wines. Serious producers plant multiple clones for complexity.",
    why: "Clonal choice at planting locks in stylistic direction for 40+ years.",
    when: "New planting conversations. Style analysis of an existing block.",
    ruleOfThumb: "Multiple clones planted in the same block → more complex wine potential. Single clone → cleaner, more focused.",
  },
  {
    id: "vit-own-rooted",
    term: "Own-rooted vs grafted vines",
    category: "viticulture",
    sop: "Own-rooted vines: Vitis vinifera scion planted directly, no rootstock. Phylloxera-vulnerable — only viable in phylloxera-free zones (much of South Australia, e.g. Barossa) or on genuinely resistant sand soils. Grafted: universal outside phylloxera-free zones.",
    plain: "Some Australian regions (Barossa especially) haven't had phylloxera, so they can plant vines directly on their own roots. Everywhere else, the vines are grafted. Own-rooted vines are romanticised — they don't necessarily make better wine, but they're rarer.",
    why: "Marketing angle for old-vine own-rooted material. Also a real biosecurity risk story.",
    when: "Barossa old-vine conversations. Any 'ungrafted' claim on a bottle.",
    ruleOfThumb: "Phylloxera-free zones (SA outside Adelaide Hills): own-rooted viable. Everywhere else: grafted.",
  },
  {
    id: "vit-variety-match",
    term: "Variety-site matching",
    category: "viticulture",
    sop: "Selection of grape variety to match a site's climate (GST), soil, water regime, and disease pressure. Established relationships: Riesling on cool-climate limestone/slate (Mosel, Eden Valley). Cabernet on warm-temperate gravel/terra rossa (Bordeaux, Coonawarra). Nebbiolo on limestone hillsides at high elevation (Piedmont).",
    plain: "Every variety has climates and soils it does its best work in. Riesling wants cool and stony. Cabernet wants warm and gravelly. Planting the wrong variety on the wrong site = 40 years of average wine.",
    why: "The biggest single mistake in Australian planting decisions over the last 40 years.",
    when: "New plantings. Vineyard purchases. Any conversation about a struggling block.",
    ruleOfThumb: "GST + soil + water + disease pressure. All four have to fit. Compromise on one — you'll wish you hadn't.",
  },
  {
    id: "vit-canopy",
    term: "Canopy management — VSP / sprawl / Scott Henry",
    category: "viticulture",
    sop: "Vine canopy training systems. VSP (Vertical Shoot Positioning): shoots trained upward, common for cool-climate varieties. Sprawl: unmanaged canopy shading fruit — used in warm sites for sun protection. Scott Henry: divided canopy (up + down), higher yield per hectare.",
    plain: "How you train the vine's shoots. Straight up (VSP) is standard for cool climates and machine harvest. Let-it-sprawl for hot sites where the leaves shade the fruit. Divided canopy (Scott Henry) if you need more crop off the same land.",
    why: "Canopy choice affects yield, ripening speed, disease pressure, and mechanisation.",
    when: "Any conversation about vineyard design or reworking an old block.",
    ruleOfThumb: "Cool climate: VSP. Hot climate: sprawl. High-yield contract fruit: Scott Henry.",
  },
  {
    id: "vit-pruning",
    term: "Pruning styles — spur / cane / cordon",
    category: "viticulture",
    sop: "Winter pruning determines the following season's bud count and shoot distribution. Spur pruning: short 1–2 bud cuts on a cordon — mechanised-friendly. Cane pruning: retention of 8–12 bud canes replaced yearly — labour-intensive, precision-friendly. Cordon: permanent horizontal arm from which spurs grow.",
    plain: "How the vine is cut back each winter. Spur pruning is fast and mechanical-friendly. Cane pruning is by hand and gives the winemaker more control. Every serious boutique cane-prunes.",
    why: "Pruning style signals a vineyard's positioning on quality vs volume.",
    when: "Vineyard tours. Grape sourcing conversations. Grower relationships.",
    ruleOfThumb: "Spur = volume + mechanised. Cane = premium + hand-worked.",
  },
  {
    id: "vit-vine-balance",
    term: "Vine balance (Ravaz index)",
    category: "viticulture",
    sop: "Ratio of yield (kg fruit) to pruning weight (kg cane). Ravaz index of 5–10 indicates balance. Below 5: vine over-cropped, ripening compromised. Above 10: vine over-vigorous, canopy dominant, fruit shaded.",
    plain: "The vine has to balance how much fruit it carries against how much wood it grows. Too much fruit = won't ripen. Too much leaf = fruit hides in shade and stays green. A healthy vine is somewhere in the middle.",
    why: "The one number that predicts whether a vineyard will produce ripe fruit reliably.",
    when: "Post-pruning assessment. Any conversation about vine vigour.",
    ruleOfThumb: "Ravaz 5–10 = balanced. Below 5 = under-cropped or over-vigorous. Above 10 = over-cropped.",
  },
  {
    id: "vit-yield-restriction",
    term: "Yield restriction — cluster thinning / shoot thinning",
    category: "viticulture",
    sop: "Green harvest interventions to reduce crop load and concentrate remaining berries. Shoot thinning: removal of surplus shoots at bud-break to reduce competition. Cluster thinning: bunch removal typically at véraison to concentrate the remainder.",
    plain: "Drop some grapes on the ground to make the remaining ones more concentrated. Sounds wasteful — it's actually how the most concentrated reds are made. Done at bud-break (shoot thin) or véraison (cluster thin).",
    why: "The single most impactful decision on wine concentration and cost per bottle.",
    when: "Winemaker asks 'can you drop the crop?' — this is what that means.",
    ruleOfThumb: "Premium boutique: 6–8 t/ha post-thinning. Volume: 12+ t/ha unmanaged.",
  },
  {
    id: "vit-bud-fruitfulness",
    term: "Bud fruitfulness",
    category: "viticulture",
    sop: "The number of inflorescences (bunch primordia) formed within each dormant bud, determined during the previous growing season. Affected by sunlight exposure, temperature, and vine stress at the moment of bud formation.",
    plain: "This year's crop was actually decided last year — inside each bud, the vine formed baby flower clusters that determine how many bunches you'll get. Last year's growing conditions matter this year.",
    why: "Explains why a hot dry summer can mean a small crop TWO years running.",
    when: "Any conversation about vintage prediction or unexpected yield.",
    ruleOfThumb: "Dry hot summer = low bud fruitfulness = smaller crop next year. Track this.",
  },
  {
    id: "vit-phenology",
    term: "Phenological stages — budburst / flowering / véraison / harvest",
    category: "viticulture",
    sop: "Four key phenological milestones. Budburst (spring): dormant buds open. Flowering (early summer): inflorescences bloom. Véraison (mid-summer): berries begin colour change and softening. Harvest: variable timing based on target sugar/acid/phenolic maturity.",
    plain: "The vine's calendar. Budburst = leaves appear (early October in Australia). Flowering = late November. Véraison = colour change in January. Harvest = Feb-May depending on variety and site.",
    why: "Phenology tracking is how growers predict harvest timing 90–120 days out.",
    when: "Any grower conversation. Harvest planning.",
    ruleOfThumb: "Harvest = véraison + 40–60 days for premium reds. Longer in cool climates.",
  },
  {
    id: "vit-gdd",
    term: "GDD — Growing Degree Days",
    category: "viticulture",
    sop: "Cumulative heat units above 10°C base temperature, summed daily across the growing season (Oct–Apr in Southern Hemisphere). Amerine-Winkler classification: Region I (<1,389 GDD) coolest through Region V (>2,222 GDD) hottest.",
    plain: "A running heat total for the season. Every day above 10°C, add the temperature above 10 to the running total. Cool regions like Yarra hit ~1,300. Hot regions like Riverland hit 2,200+. Determines what varieties will ripen.",
    why: "The single number that classifies climate for viticulture purposes.",
    when: "Regional style discussions. Variety-site matching.",
    ruleOfThumb: "Region I (Yarra, Tasmania): Pinot, Chardonnay. Region III (Barossa): Shiraz. Region V (Riverland): bulk anything.",
  },
  {
    id: "vit-water-stress",
    term: "Water stress — regulated deficit irrigation",
    category: "viticulture",
    sop: "Controlled water restriction post-fruit-set to reduce berry size and concentrate flavour compounds. Measured via mid-day leaf water potential (Ψleaf) at −1.2 to −1.5 MPa target. Excessive stress compromises photosynthesis and phenolic accumulation.",
    plain: "Deliberately underwatering the vine — but only after the berries have set. Small berries = concentrated flavour. Overdo it and the vine shuts down and the fruit gets stuck green.",
    why: "One of the highest-leverage decisions a premium red producer makes.",
    when: "Any premium warm-climate vineyard conversation. Barossa, McLaren Vale in particular.",
    ruleOfThumb: "Post-fruit-set through véraison: strategic stress. Post-véraison: reduce stress to complete ripening.",
  },
  {
    id: "vit-powdery-mildew",
    term: "Powdery mildew (Erysiphe necator)",
    category: "viticulture",
    sop: "Ubiquitous fungal pathogen affecting shoots, leaves, and berries. Requires no free water — thrives in moderate temperature + humidity + shading. Symptoms: white/grey powdery growth. Control: sulfur (organic-compatible), synthetic fungicides on rotation to prevent resistance.",
    plain: "The most common vineyard disease. White dusty growth on leaves and berries. Loves shaded, humid conditions. Every vineyard sprays for it — sulfur if organic, synthetic if conventional.",
    why: "Ignore it and lose 30-100% of a crop. Universal viticulture headache.",
    when: "Any conversation about spray programs or organic certification.",
    ruleOfThumb: "Sulfur every 10-14 days from budburst through véraison. Rotate synthetics to prevent resistance.",
  },
  {
    id: "vit-downy-mildew",
    term: "Downy mildew (Plasmopara viticola)",
    category: "viticulture",
    sop: "Fungal pathogen requiring free water for infection cycle. Symptoms: yellow 'oil spots' on leaf upper surface, white downy sporulation underside. Aggressive in wet springs. Control: copper (organic) or systemic phosphonate/QoI fungicides.",
    plain: "The wet-weather disease. Needs actual water on the leaves to spread. Kills fast in a rainy spring. Yellow oil spots on top of the leaf, white fluff underneath. Copper is the organic answer; systemic sprays for conventional.",
    why: "Vintage-defining disease in wet years. Hunter Valley especially vulnerable.",
    when: "Any wet spring conversation. Hunter Valley or humid-region conversations.",
    ruleOfThumb: "Copper 3-5 kg/ha every 10-14 days when wet weather forecast. Time to rain event.",
  },
  {
    id: "vit-botrytis",
    term: "Botrytis — noble vs bunch rot",
    category: "viticulture",
    sop: "Botrytis cinerea. Two expressions: (1) Noble rot — concentrated dehydration in low-humidity conditions on ripe berries, prized for sweet wine (Sauternes, botrytised Riesling). (2) Grey/bunch rot — destructive expression in humid/wet conditions on damaged berries.",
    plain: "Same fungus, two very different outcomes. In dry conditions on ripe grapes, it sucks water out and concentrates sugar — that's how Sauternes and sticky Riesling are made. In wet conditions on damaged fruit, it just rots the crop.",
    why: "The rare disease that's either a gift or a disaster depending on the weather.",
    when: "Late-vintage rain conversations. Sweet-wine style conversations.",
    ruleOfThumb: "Cool + dry post-véraison = noble. Warm + wet = grey rot disaster.",
  },
  {
    id: "vit-spray-programs",
    term: "Spray programs — organic vs conventional",
    category: "viticulture",
    sop: "Conventional: synthetic systemic fungicides (QoIs, triazoles, phosphonates) on rotation, high efficacy, resistance management essential. Organic: sulfur (powdery mildew) + copper (downy mildew) only, plus biological controls. Higher spray frequency (10–20 rounds/season vs 6–10 conventional).",
    plain: "Organic vineyards spray a LOT — just with allowed materials (sulfur, copper). Conventional vineyards spray less but with stronger stuff. Organic isn't zero-spray; it's different-spray.",
    why: "Every 'organic wine' conversation eventually asks about sprays. Have the right answer ready.",
    when: "Any certification conversation. Any organic-curious client.",
    ruleOfThumb: "Organic ≠ unsprayed. Organic = sulfur + copper + more passes. Certification is process, not zero-input.",
  },
];
